version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      # - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
      
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data
    networks:
      - fullstack

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      - ENVIROMENT=docker
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
      - redis
    networks:
      - fullstack

  app:
    container_name: app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 5000:5000
    networks:
      - fullstack
    volumes:
      - app_volume:/usr/src/front

volumes:
  database_dockerizing:
    driver: local
  api_volume:
  app_volume:
  redis:
    driver: local

networks:
  fullstack:
    driver: bridge