version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      # - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
      
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data
    networks:
      - fullstack

  api:
    container_name: api
    build: .
    env_file:
      - .env
    environment:
      - ENVIROMENT=docker
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
      - redis
    networks:
      - fullstack

volumes:
  database_dockerizing:
    driver: local
  api_volume:
  redis:
    driver: local

networks:
  fullstack:
    driver: bridge